### ISSUE TITLE
Crash on linux in lua code called from CtrlrPanel constructor.

### ISSUE THREAD

**Issue by keinstein** [RomanKubiak/ctrlr#181]
I've been trying to get Ctrlr running in a release build on Linux for several days, now. Some came up during this effort, but I can't figure out, what shall be wrong. As alwys anything can go wrong. Neither thread sanitizer nor Address Sanitizer helped so far. 

Can someone help with the following backtrace (x86_64 Debian GNU/Linux testing, gdb) against https://github.com/keinstein/ctrlr/commit/0bf8eb73f647b5b8d1230ed30c6a4c09769162ac?
```
(gdb) bt full
#0  0x0000555555e3ac71 in luabind::detail::object_rep::object_rep (this=0x5555573a5be8, instance=0x0, crep_=0x5555571cda88) at ../../Source/Misc/luabind/src/object_rep.cpp:38
No locals.
#1  0x0000555555e3b093 in luabind::detail::push_new_instance (L=L@entry=0x5555570bf370, cls=0x5555571cda88) at /usr/include/c++/10/new:175
        storage = 0x5555573a5be8
        result = <optimized out>
#2  0x0000555555f78a0a in luabind::detail::make_instance<CtrlrPanel*> (L=L@entry=0x5555570bf370, p=p@entry=0x55555713e910) at ../../Source/Misc/luabind/luabind/detail/make_instance.hpp:84
        dynamic = {first = <optimized out>, second = 0x55555713e910}
        cls = <optimized out>
        instance = <optimized out>
        storage = <optimized out>
#3  0x0000555555f82728 in luabind::detail::pointer_converter::apply<CtrlrPanel> (this=<synthetic pointer>, ptr=0x55555713e910, L=0x5555570bf370) at ../../Source/Misc/luabind/luabind/detail/policy.hpp:238
No locals.
#4  luabind::detail::push_aux<CtrlrPanel* const, luabind::detail::default_policy> (value=<optimized out>, L=0x5555570bf370) at ../../Source/Misc/luabind/luabind/stack.hpp:33
        cv = {<luabind::detail::pointer_converter> = {result = <optimized out>}, <No data fields>}
        cv = {<luabind::detail::pointer_converter> = {result = <optimized out>}, <No data fields>}
#5  luabind::push<CtrlrPanel* const, luabind::detail::null_type> (value=<optimized out>, L=0x5555570bf370) at ../../Source/Misc/luabind/luabind/stack.hpp:51
No locals.
#6  luabind::push<CtrlrPanel* const> (value=<optimized out>, L=0x5555570bf370) at ../../Source/Misc/luabind/luabind/stack.hpp:57
No locals.
#7  luabind::adl::index_proxy<luabind::adl::object>::operator=<CtrlrPanel*> (value=<optimized out>, this=<optimized out>) at ../../Source/Misc/luabind/luabind/detail/object.hpp:599
        pop = {m_state = <optimized out>, m_n = <optimized out>}
        pop = {m_state = <optimized out>, m_n = <optimized out>}
#8  CtrlrLuaManager::assignDefaultObjects (this=0x5555571209f0, L=0x5555570bf370) at ../../Source/Lua/CtrlrLuaManager.cpp:272
No locals.
#9  0x0000555555f83238 in CtrlrLuaManager::CtrlrLuaManager (this=0x5555571209f0, _owner=...) at ../../Source/Lua/CtrlrLuaManager.cpp:88
No locals.
#10 0x0000555555e78770 in CtrlrPanel::CtrlrPanel (this=0x55555713e910, _owner=..., panelName=..., idx=<optimized out>) at ../../Source/Core/CtrlrPanel/CtrlrPanel.cpp:56
No locals.
#11 0x0000555555e64b0b in CtrlrManager::addPanel (this=this@entry=0x555556e84570, savedState=..., showUI=showUI@entry=true) at ../../Source/Core/CtrlrManager/CtrlrManager.cpp:174
        panel = <optimized out>
#12 0x0000555555ac33b4 in CtrlrEditor::perform (this=<optimized out>, info=...) at ../../Source/UIComponents/CtrlrApplicationWindow/CtrlrEditorApplicationCommandsHandlers.cpp:45
No locals.
#13 0x0000555555c012ca in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const (fd=4, __closure=0x555556e60c18) at ../../JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:43
        msg = {referencedObject = 0x5555571208d0}
        this = 0x555556e60ea0
        this = <optimized out>
        msg = {referencedObject = <optimized out>}
#14 std::__invoke_impl<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(std::__invoke_other, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) (__f=...) at /usr/include/c++/10/bits/invoke.h:60
No locals.
#15 std::__invoke_r<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) (__fn=...) at /usr/include/c++/10/bits/invoke.h:153
No locals.
#16 std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/10/bits/std_function.h:291
No locals.
#17 0x0000555555bfff04 in std::function<void (int)>::operator()(int) const (__args#0=<optimized out>, this=0x555556e60c18) at /usr/include/c++/10/bits/std_function.h:622
No locals.
#18 juce::InternalRunLoop::dispatchPendingEvents (this=0x555556e60b90) at ../../JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:186
        insideFdReadCallback = {value = <optimized out>, originalValue = <optimized out>}
        fdAndCallback = {first = 4, second = {<std::_Maybe_unary_or_binary_function<void, int>> = {<std::unary_function<int, void>> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x555556e60ea0, _M_const_object = 0x555556e60ea0, _M_function_pointer = 0x555556e60ea0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x555556e60ea0, this adjustment 140737488348152}, _M_pod_data = "\240\016\346VUU\000\000\370\343\377\377\377\177\000"}, _M_manager = 0x555555c00a90 <std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555c011d0 <std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&)>}}
        __for_range = std::vector of length 2, capacity 16 = {{first = 4, second = {<std::_Maybe_unary_or_binary_function<void, int>> = {<std::unary_function<int, void>> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x555556e60ea0, _M_const_object = 0x555556e60ea0, _M_function_pointer = 0x555556e60ea0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x555556e60ea0, this adjustment 140737488348152}, _M_pod_data = "\240\016\346VUU\000\000\370\343\377\377\377\177\000"}, _M_manager = 0x555555c00a90 <std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555c011d0 <std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&)>}}, {first = 5, second = {<std::_Maybe_unary_or_binary_function<void, int>> = {<std::unary_function<int, void>> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x555556e61470, _M_const_object = 0x555556e61470, _M_function_pointer = 0x555556e61470, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x555556e61470, this adjustment 378}, _M_pod_data = "p\024\346VUU\000\000z\001\000\000\000\000\000"}, _M_manager = 0x555555cdbfe0 <std::_Function_handler<void(int), juce::XWindowSystem::initialiseXDisplay()::<lambda(int)> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>}, _M_invoker = 0x555555d23d10 <std::_Function_handler<void(int), juce::XWindowSystem::initialiseXDisplay()::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&)>}}}
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_begin = 
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_end = 
        fd = 4
        pfd = @0x555556b6c910: {fd = 4, events = 1, revents = 0}
        __for_range = std::vector of length 2, capacity 2 = {{fd = 4, events = 1, revents = 0}, {fd = 5, events = 1, revents = 0}}
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_begin = 
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_end = 
        sl = {lock_ = <optimized out>}
        eventWasSent = <optimized out>
        sl = {lock_ = <optimized out>}
        eventWasSent = <optimized out>
        pfd = <optimized out>
        __for_range = <optimized out>
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_begin = 
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_end = 
        fd = <optimized out>
        fdAndCallback = <optimized out>
        __for_range = <optimized out>
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_begin = 
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_end = 
        insideFdReadCallback = {value = <optimized out>, originalValue = <optimized out>}
        deferredRegisterEvent = <optimized out>
        __for_range = <optimized out>
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_begin = 
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_end = 
#19 juce::MessageManager::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=false) at ../../JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:300
        runLoop = 0x555556e60b90
#20 0x0000555555c000df in juce::MessageManager::runDispatchLoop (this=0x555556e60b20) at ../../JUCE/modules/juce_events/messages/juce_MessageManager.cpp:128
No locals.
#21 0x00005555558017c6 in juce::JUCEApplicationBase::main () at ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:262
        libraryInitialiser = {<No data fields>}
        app = std::unique_ptr<juce::JUCEApplicationBase> = {get() = 0x555556e60b50}
#22 0x00007ffff76b1d0a in __libc_start_main (main=0x55555574db00 <main(int, char**)>, argc=1, argv=0x7fffffffe568, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe558) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -5461300467646172478, 93824997864384, 0, 0, 0, -2206549096112164158, -2206532506541329726}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7fffffffe568}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#23 0x0000555555ab33ea in _start ()
No symbol table info available.
```
Btw. All patches are intended for upstream usage.

**Comment by keinstein** [comment]
I did some investigations.

When I switch to lua5.2 (losing bits and usb and getting bits32) and luabind from my Debian system Ctrlr seems to work normally, after I remove the duplicate library initialization (see https://github.com/keinstein/ctrlr/commit/7e752af1f4005dcb47f1553195b1d7a1353fadb4 and https://github.com/keinstein/ctrlr/commit/b226fa087a4522460aac4769292267f0bfee3fdb).

So the problem lies either in the patched lua, luabind or in the patched libusb. For libusb lua has been patched just in a very view lines. So it should be easy to remove it. I didn't try so far. The bit library has been copied into the lua code. So it is probably more effort to remove it. As it seems to has disappeared from the internet, it should be probably replaced by bit32 which comes with lua from 5.2.

For USB support I found https://github.com/LuaDist/lualibusb which seems to be a thin layer between libusb and lua, while the current Ctrlr impementation is a very old modified libusb which may or may not play well or interfere with the host supplied libusb. While the API stays very stable over a long time  the ABI may change, especially for internal functions which are not ment to be exposed to the outside. And there are also driver/kernel changes which may render old libraries unusable on modern systems.

So I'd suggest to separate libusb, lua and the bit package. And use the packages that are provided by the underlying Linux distribution. I think both, libusb support and bitwise operators will lead to incompatible changes. If help is wanted in this path, I'm willing to give a hand. But I'm not willing to dig too deep into lua or this libusb/lua glue code mixture.
