### ISSUE TITLE
Mismatch in types of new and delete of some objects

### ISSUE THREAD

**Issue by keinstein** [RomanKubiak/ctrlr#425]
Backtrace:
```
=================================================================
==84659==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x6020002002d0 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   16 bytes;
  size of the deallocated type: 8 bytes.
    #0 0x555556ca0317 in operator delete(void*, unsigned long) (/nomirror/tobias/build/ctrlr/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x174c317)
    #1 0x555557a021cd in std::default_delete<CtrlrNative>::operator()(CtrlrNative*) const /usr/include/c++/11/bits/unique_ptr.h:85
    #2 0x555557a00130 in std::unique_ptr<CtrlrNative, std::default_delete<CtrlrNative> >::~unique_ptr() /usr/include/c++/11/bits/unique_ptr.h:361
    #3 0x5555579ec385 in CtrlrManager::~CtrlrManager() ../../Source/Core/CtrlrManager/CtrlrManager.cpp:45
    #4 0x5555579ec52b in CtrlrManager::~CtrlrManager() ../../Source/Core/CtrlrManager/CtrlrManager.cpp:45
    #5 0x555556d90db6 in juce::ContainerDeletePolicy<CtrlrManager>::destroy(CtrlrManager*) ../../JUCE/modules/juce_core/memory/juce_ContainerDeletePolicy.h:54
    #6 0x555556d90080 in juce::ScopedPointer<CtrlrManager>::reset() ../../JUCE/modules/juce_core/memory/juce_ScopedPointer.h:98
    #7 0x555556d8f6c1 in juce::ScopedPointer<CtrlrManager>::~ScopedPointer() ../../JUCE/modules/juce_core/memory/juce_ScopedPointer.h:56
    #8 0x555556d7ea4c in CtrlrProcessor::~CtrlrProcessor() ../../Source/Plugin/CtrlrProcessor.cpp:64
    #9 0x555556d7eabb in CtrlrProcessor::~CtrlrProcessor() ../../Source/Plugin/CtrlrProcessor.cpp:64
    #10 0x555556cf6ec8  (/nomirror/tobias/build/ctrlr/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x17a2ec8)
    #11 0x555556ce8f36 in CtrlrStandaloneWindow::deleteFilter() ../../Source/Core/StandaloneWrapper/CtrlrStandaloneWindow.cpp:142
    #12 0x555556ce8246 in CtrlrStandaloneWindow::~CtrlrStandaloneWindow() ../../Source/Core/StandaloneWrapper/CtrlrStandaloneWindow.cpp:89
    #13 0x555556ce82c1 in CtrlrStandaloneWindow::~CtrlrStandaloneWindow() ../../Source/Core/StandaloneWrapper/CtrlrStandaloneWindow.cpp:90
    #14 0x555556ce6292  (/nomirror/tobias/build/ctrlr/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x1792292)
    #15 0x555556ce579f  (/nomirror/tobias/build/ctrlr/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x179179f)
    #16 0x5555572f7c53 in juce::JUCEApplicationBase::shutdownApp() ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:325
    #17 0x5555572f7776 in juce::JUCEApplicationBase::main() ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:267
    #18 0x5555572f759d in juce::JUCEApplicationBase::main(int, char const**) ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:241
    #19 0x555556ce00ec in main ../../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp:48
    #20 0x7ffff742c7ec in __libc_start_main ../csu/libc-start.c:332
    #21 0x555556c14049  (/nomirror/tobias/build/ctrlr/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x16c0049)

0x6020002002d0 is located 0 bytes inside of 16-byte region [0x6020002002d0,0x6020002002e0)
allocated by thread T0 here:
    #0 0x555556c9f497 in operator new(unsigned long) (/nomirror/tobias/build/ctrlr/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x174b497)
    #1 0x5555581a9cee in CtrlrNative::getNativeObject(CtrlrManager&) ../../Source/Native/CtrlrNative.cpp:22
    #2 0x555557a0df9f in CtrlrManager::initEmbeddedInstance() ../../Source/Core/CtrlrManager/CtrlrManagerInstance.cpp:39
    #3 0x555556d7e4a0 in CtrlrProcessor::CtrlrProcessor() ../../Source/Plugin/CtrlrProcessor.cpp:43
    #4 0x555556d7da59 in createPluginFilter() ../../Source/Plugin/CtrlrProcessor.cpp:16
    #5 0x555556ce6c66 in CtrlrStandaloneWindow::CtrlrStandaloneWindow(juce::String const&, juce::Colour const&) ../../Source/Core/StandaloneWrapper/CtrlrStandaloneWindow.cpp:16
    #6 0x555556ce4f19  (/nomirror/tobias/build/ctrlr/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x1790f19)
    #7 0x5555572f7a22 in juce::JUCEApplicationBase::initialiseApp() ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:298
    #8 0x5555576d5949 in juce::JUCEApplication::initialiseApp() ../../JUCE/modules/juce_gui_basics/application/juce_Application.cpp:92
    #9 0x5555572f7733 in juce::JUCEApplicationBase::main() ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:257
    #10 0x5555572f759d in juce::JUCEApplicationBase::main(int, char const**) ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:241
    #11 0x555556ce00ec in main ../../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp:48
    #12 0x7ffff742c7ec in __libc_start_main ../csu/libc-start.c:332

SUMMARY: AddressSanitizer: new-delete-type-mismatch (/nomirror/tobias/build/ctrlr/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x174c317) in operator delete(void*, unsigned long)
==84659==HINT: if you don't care about these errors you may set ASAN_OPTIONS=new_delete_type_mismatch=0
==84659==ABORTING
```

**Comment by keinstein** [comment]
The first discovery: 
CtrlrLinux has a destructor but CtrlrNative has no virtual destructor.
I'm adding it, maybe this helps.

**Comment by keinstein** [comment]
It seems to work.
